# Generated by Django 5.1.5 on 2025-04-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_crafts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_crafts',
        ),
    ]
