# Generated by Django 5.1.5 on 2025-04-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_alter_craftideamodel_video'),
        ('accounts', '0007_remove_profile_liked_crafts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_crafts',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='Media.craftideamodel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_crafts',
            field=models.ManyToManyField(blank=True, related_name='created_by', to='Media.craftideamodel'),
        ),
    ]
