# Generated by Django 5.0.1 on 2025-04-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftideamodel',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
