# Generated by Django 5.1.7 on 2025-04-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_rename_movie_craftideareview_craft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftideamodel',
            name='director',
        ),
        migrations.RemoveField(
            model_name='craftideamodel',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='craftideamodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='craftideamodel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='craftideamodel',
            name='year',
        ),
        migrations.AddField(
            model_name='craftideamodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images/'),
        ),
    ]
