# Generated by Django 5.0.1 on 2025-04-27 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_alter_craftideamodel_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='craftideamodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_crafts', to=settings.AUTH_USER_MODEL),
        ),
    ]
