# Generated by Django 5.1.7 on 2025-04-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0003_remove_craftideamodel_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftideamodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
