# Generated by Django 5.1.7 on 2025-04-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0003_remove_craftideamodel_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftideamodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='movie_videos/'),
        ),
    ]
