# Generated by Django 5.1.7 on 2025-04-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0004_alter_craftideamodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftideamodel',
            name='thing',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
