# Generated by Django 5.1.7 on 2025-04-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0005_craftideamodel_thing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftideamodel',
            name='thing',
        ),
        migrations.AlterField(
            model_name='craftideamodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
