# Generated by Django 5.1.7 on 2025-04-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0006_remove_craftideamodel_thing_alter_craftideamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftideamodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
