# Generated by Django 5.1.7 on 2025-04-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0007_alter_craftideamodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftideamodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='movie_videos/'),
        ),
    ]
