"""
Django settings for P2CraftProject project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print("This is base directory: ", BASE_DIR)
# print(concated) # TODO Take this away


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hsux8ul=lbsjb+&f_wu!sqb_)xqk0f(8eaeh=&w91ophumtyf5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Crafts', # just added but doesn't work since it isn't a model yet

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CraftSite.urls'

TEMPLATES_CRAFTSITE = os.path.join(BASE_DIR, 'CraftSite','templates')
TEMPLATES_CRAFTS = os.path.join(BASE_DIR, 'Crafts/templates')
# I want to automate this process so multiple templates always go to the correct location
# But for the time being, everytime we make a new template, it has to be made here, and then put into the list of 'DIRS' in
# TEMPLATES
#

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
print("new base directory: ", BASE_DIR)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [os.path.join(BASE_DIR, 'templates')], # [BASE_DIR, TEMPLATES_CRAFTSITE, TEMPLATES_CRAFTS], # TODO this didn't work
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CraftSite.wsgi.application'

BASE_DIR = Path(__file__).resolve().parent.parent
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


"""
Got it! Thanks for the detailed explanation. To ensure that you don't have to update the DIRS setting in your settings.py file every time you add a new app, you can use a more dynamic approach. Instead of listing each app's template directory individually, you can set up a single directory that will include all your templates.

Here's how you can do it:

Create a new directory called templates at the root of your project (i.e., inside the Location directory).
Inside this templates directory, create subdirectories for each app (e.g., Crafts, Things).
Your directory structure will look like this:

Location/
    manage.py
    CraftSite/
        settings.py
    Crafts/
        views.py
        templates/
            Crafts/
                index.html
    Things/
        templates/
            Things/
                things.html
    templates/
        Crafts/
        Things/
Move the Crafts/templates/Crafts and Things/templates/Things directories into the new templates directory at the root level.

Update your settings.py file to include the new templates directory in the DIRS setting:

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
With this setup, you only need to add your templates to the appropriate subdirectory inside the templates directory, and Django will automatically find them without needing to update the DIRS setting each time.

Let me know if you need any further assistance!
"""